### ISSUE TITLE
PlayerBar issue

### ISSUE THREAD

**Issue by starsice** [physia/kflutter#12]
The position display is abnormal, after the playback exceeds 60 seconds

![捕获0505](https://user-images.githubusercontent.com/34392774/166873173-04748ddd-ec89-400e-a45a-d09d1ce17915.PNG)

**Comment by mohamadlounnas** [comment]
Are you using the main package?
Can you give more information?
Platform?

**Comment by starsice** [comment]
[https://physia.github.io/kflutter/kplayer/online_example/index.html](url)，same question. You can drag the progress bar。

**Comment by mohamadlounnas** [comment]
Thanks @starsice 
bug fixed
use the latest version

[live example](https://physia.github.io/kflutter/kplayer/online_example/index.html)
you may need to clear browser cache
