### ISSUE TITLE
player.back()

### ISSUE THREAD

**Issue by welitonsousa** [physia/kflutter#14]
I ran the "fvm flutter pub upgrade"
and there was a problem when calling a method that does not exist

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/64853142/167849710-53560e19-0cca-4ec8-8640-cb45aaffaf02.png">

**Comment by mohamadlounnas** [comment]
it was work before the upgrade?

**Comment by welitonsousa** [comment]
yes

Em qua., 11 de mai. de 2022 às 17:21, mohamad lounnas <
***@***.***> escreveu:

**Comment by mohamadlounnas** [comment]
can u send the full code?

**Comment by runesign** [comment]
oh, it seems we the same problem
<img width="960" alt="2022-05-12" src="https://user-images.githubusercontent.com/43579838/168036743-15c07828-8466-46a7-bd98-b9aad6e6c2dd.png">

**Comment by guillaumeboehm** [comment]
I dug a little bit in dart_vlc and it seems back was changed to previous. Although I'm not certain I didn't take a very good look.

**Comment by guillaumeboehm** [comment]
Until 0.2.0 is supported forcing "dart_vlc_ffi: <0.1.6" in pubspec fixes the issue.

**Comment by mohamadlounnas** [comment]
> Until 0.2.0 is supported forcing "dart_vlc_ffi: <0.1.6" in pubspec fixes the issue.
@guillaumeboehm 
did dependency_overrides solve the problem?

**Comment by mohamadlounnas** [comment]
@runesign @welitonsousa @guillaumeboehm 
until next version, currently use latest version from github
```
dependency_overrides:
  dart_vlc:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      ref: master
```

**Comment by guillaumeboehm** [comment]
@mohamadlounnas Oh I wan't aware of dependency_overrides, thanks. Setting dart_vlc to ^0.2.0 with it worked fine for me.

**Comment by mohamadlounnas** [comment]
@guillaumeboehm 
u welcome,
if u search deeply about pubspec.yaml u will find interesting things

Since this issue is not related to this same package we will close the issue.
To avoid this problem in future, we will not let dart_vlc will specify the version of its dependencies
instaid we well override it in Kplayer packege.

Thank you guys @guillaumeboehm @runesign  @welitonsousa
