### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by jeejeestudio** [physia/kflutter#17]
Hi,
i've got a few questions, don't know where to ask them else than here as I can get it from the information available. (latest version)
-How can I change the buttons to white?
Now I have it in a container so I can change the back groundcolor else I don't see the buttons, but actually I want white user controls on black background. I'm not using a white or black modus, it's just black.
```
Container(color: Colors.blue[100],
                       child: PlayerBar(player: player1, options: []))
```
-I have it playing a mp3 from network, but I don't hear sound. (on Android, not tested with other platforms yet)
-What options are available (see the piece of code above) ?
-How do I prevent automatic playing, it must load the mp3 but not auto-play.
-If a second player starts, other players must stop how do I do that.

Thanks very much for your help.
Jerry

**Comment by mohamadlounnas** [comment]
hi @jeejeestudio 
>  How can I change the buttons to white?

i well add styling configs later but know you can change it by wraping the `PlayerBar` on `Theme` and play with it.
```dart
Container(
    color: Colors.blue[100],
    child: Theme(
        data: // TODO ....
        child: PlayerBar(
            player: player1,
            options: [],
        ),
    ),
)
```
> What options are available (see the piece of code above) ?

the `options` is just list of widget 
![image](https://user-images.githubusercontent.com/22839194/170821908-466351ba-695f-465e-b41d-d591fb1783f3.png)
style options and other thing is not ready yet
i use it in the example to add Dark mode switch
example:
```dart
         PlayerBar(player: player, options: [
                SwitchListTile(
                  secondary: const Icon(Icons.brightness_2),
                  title: const Text("Dark mode"),
                );
          ]),
```

> -How do I prevent automatic playing, it must load the mp3 but not auto-play.

just set autoPlay to false 
example:
```dart
var player = Player.asset("/assets/sound.mp3",autoPlay: false);
```

> -If a second player starts, other players must stop how do I do that.

currently you need to dispose the previous player
for example:
```dart
var player = Player.asset("/assets/sound.mp3",autoPlay: false);
player.play()
// ...
player.dispose();
player = Player.network("www.example.com/file.mp3");
```
but i plan it to add somthing like `player.reuse()` to re use player by defrent source
also i will add `Player.disposeAll()` to easly dispose All players
you can acces to all players by `PlayerController.players` return `List<PlayerController>`

If you have any other questions, feel free to ask.

**Comment by mohamadlounnas** [comment]
> -I have it playing a mp3 from network, but I don't hear sound. (on Android, not tested with other platforms yet)

can you send more information?

**Comment by jeejeestudio** [comment]
Hello Mohamad, 
thanks very much for your reply.
I do have sound, it was a mistake from me, had a setting not correct with my audio.
I have max 6 players in my app where one can scroll down to see the next, and listen to the next song. So if one start playing the next song all others should pause or stop. But the previous one has to stay available.
If I dispose a player, is it then gone or is it reusable?
Well going to play with some setting you, found the autoPlay: false in your example.
Thank you!

Regards,
Jerry

**Comment by mohamadlounnas** [comment]
hi Jerry
if you want to just pause the other players just use this before the play code:
```dart
PlayerController.palyers.forEach((_player)=>_player.pause());
```
this will pause all players
the `dispose()` method destroy the player, `pause` just pause the instance of player

in v0.2.4 you can use `player.others` to get list of all other players 
example:
```dart
player.others.forEach((player) => player.pause());
```
also i opened the [discussions](https://github.com/physia/kflutter/discussions) on this repository.

thank you

**Comment by mohamadlounnas** [comment]
hi Jerry
if you want to just pause the other players just use this before the play code:
```dart
PlayerController.palyers.forEach((_player)=>_player.pause());
```
this will pause all players
the `dispose()` method destroy the player, `pause` just pause the instance of player

in v0.2.4 you can use `player.others` to get list of all other players 
example:
```dart
player.others.forEach((player) => player.pause());
```
also i opened the [discussions](https://github.com/physia/kflutter/discussions) on this repository.

thank you

**Comment by mohamadlounnas** [comment]
hi Jerry
if you want to just pause the other players just use this before the play code:
```dart
PlayerController.palyers.forEach((_player)=>_player.pause());
```
this will pause all players
the `dispose()` method destroy the player, `pause` just pause the instance of player

in v0.2.4 you can use `player.others` to get list of all other players 
example:
```dart
player.others.forEach((player) => player.pause());
```
also i opened the [discussions](https://github.com/physia/kflutter/discussions) on this repository.

thank you

**Comment by jeejeestudio** [comment]
Hi Mohamad,

ok thank you, I will play with it and ask a next question in discussions you've opened.
Thanks very much for your help.
