### ISSUE TITLE
Using with stateful widgets

### ISSUE THREAD

**Issue by sarpde** [physia/kflutter#2]
Hello,

I'm relatively new to Flutter so not very familiar with extending classes and all. I tried your package to help me with a stack Z-index issue but couldn't make it work. I want to be able to move the box over the other one, so trying to change the index (to 100) when moving the box (you can see the index I'm trying to set while moving the box).

Any idea how can I solve this?

`import 'package:flutter/material.dart';
import 'package:indexed/indexed.dart';

class NewBoard extends StatefulWidget {
  const NewBoard({Key? key}) : super(key: key);

  @override
  _NewBoardState createState() => _NewBoardState();
}

class _NewBoardState extends State<NewBoard> {
  List index = [0, 1];

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 300,
      height: 300,
      child: Indexer(
        children: [
          MoveableStackItem(
              positionIndex: index[0], color: Colors.blue, index: 1),
          MoveableStackItem(
              positionIndex: index[1], color: Colors.orange, index: 0),
          Positioned(
            top: 160,
            child: ElevatedButton(
                onPressed: () {
                  setState(() {
                    index =
                        index[0] == 0 ? List.from([1, 0]) : List.from([0, 1]);
                  });
                },
                child: Text('swap')),
          )
        ],
      ),
    );
  }
}

class MoveableStackItem extends StatefulWidget implements IndexedInterface {
  int index;
  final int positionIndex;
  final Color color;

  MoveableStackItem({
    Key? key,
    required this.positionIndex,
    required this.color,
    required this.index,
  }) : super(key: key);

  @override
  _MoveableStackItemState createState() => _MoveableStackItemState();
}

class _MoveableStackItemState extends State<MoveableStackItem> {
  double xPosition = 0;
  double yPosition = 0;
  Color color = Colors.black;

  @override
  void initState() {
    xPosition = widget.positionIndex * 40 + 10;
    yPosition = 10;
    color = widget.color;
    super.initState();
  }

  @override
  void didUpdateWidget(MoveableStackItem oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.positionIndex != oldWidget.positionIndex) {
      xPosition = widget.positionIndex * 40 + 10;
      yPosition = 10;
    }
  }

  @override
  Widget build(BuildContext context) {
    var index = widget.index;
    print(index);
    print(widget.positionIndex);
    return Indexed(
      index: index,
      key: UniqueKey(),
      child: AnimatedPositioned(
        duration: const Duration(milliseconds: 250),
        curve: Curves.easeOutCubic,
        top: yPosition,
        left: xPosition,
        child: Listener(
          onPointerUp: (e) {
            setState(() {
              xPosition = widget.positionIndex * 40.0 + 10;
              yPosition = 10.0;
              widget.index = 0;
            });
          },
          child: GestureDetector(
            onTap: () {
              setState(() {
                widget.index = 100;
              });
            },
            onPanUpdate: (tapInfo) {
              setState(() {
                xPosition += tapInfo.delta.dx;
                yPosition += tapInfo.delta.dy;
                widget.index = 100;
              });
            },
            child: Container(
              width: 30,
              height: 30,
              color: color,
              child: Text(widget.index.toString()),
            ),
          ),
        ),
      ),
    );
  }
}
`

https://user-images.githubusercontent.com/4488521/133305754-21f076b0-e560-4491-9c1a-4f53be834de9.mov

**Comment by mohamadlounnas** [comment]
hi bro,
the index need to be changed in the widget who contains "Indexer"
you made some mistakes
in this case you dont need to extend  or implement `IndexedInterface` it just for some cases, But I will correct the example in the same way.
![Screenshot](https://user-images.githubusercontent.com/22839194/133334670-9fb874fd-e141-46ba-a8d2-5f8aef9213bb.png)
I wrote a new code:

```dart
import 'package:flutter/material.dart';
import 'package:indexed/indexed.dart';

class Item {
  final Key key;
  final Color color;
  int index;
  Item({this.index = 0, required this.key, required this.color});

  static List<Item> items = [
    Item(key: UniqueKey(), color: Colors.green),
    Item(key: UniqueKey(), color: Colors.red),
    Item(key: UniqueKey(), color: Colors.blue),
  ];
}

class NewBoard extends StatefulWidget {
  const NewBoard({Key? key}) : super(key: key);

  @override
  _NewBoardState createState() => _NewBoardState();
}

class _NewBoardState extends State<NewBoard> {
  void callback() {
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Indexer(
        children: [
          for (var item in Item.items)
            ItemWidget(key: item.key, item: item, callback: callback),
        ],
      ),
    );
  }
}

class ItemWidget extends StatefulWidget implements IndexedInterface {
  final VoidCallback callback;
  get index => item.index;
  ItemWidget({
    Key? key,
    required this.item,
    required this.callback,
  }) : super(key: key);

  // this is important
  final Item item;

  @override
  State<ItemWidget> createState() => _ItemWidgetState();
}

class _ItemWidgetState extends State<ItemWidget> {
  double positionTop = 0;

  double positionLeft = 0;
  @override
  void initState() {
    super.initState();
    positionLeft = 80 * Item.items.indexOf(widget.item).toDouble();
  }

  @override
  Widget build(BuildContext context) {
    return Positioned(
      top: positionTop,
      left: positionLeft,
      child: GestureDetector(
        onPanStart: (details) {
          setState(() {
            widget.item.index = 100;
          });
          // update the indexer
          widget.callback();
        },
        onPanUpdate: (details) {
          setState(() {
            positionTop += details.delta.dy;
            positionLeft += details.delta.dx;
          });
        },
        onPanEnd: (e) {
          setState(() {
            widget.item.index = 0;
          });
        },
        child: Container(
          width: 80,
          height: 80,
          color: widget.item.color,
          child: Center(
              child: Column(
            children: [
              Text("${widget.item.index}\n$positionTop\n$positionLeft"),
            ],
          ),),
        ),
      ),
    );
  }
}
```

**Comment by sarpde** [comment]
Thanks a lot for the quick reply and the detailed answer! :) This has helped me a lot.

**Comment by Elvincth** [comment]
Thanks for your package, I need this as well!
