### ISSUE TITLE
Kplayer error

### ISSUE THREAD

**Issue by AirtonGamer** [physia/kflutter#21]
i have an problem looping the audio and it runs only one time and it gives this log:
(Reload already in progress, ignoring request
Restarted application in 5,946ms.
flutter: Kplayer: just_audio
flutter: PlayerEvent.init
flutter: PlayerEvent.loop
flutter: PlayerEvent.play
flutter: PlayerEvent.status
AudioPlayers: Could not query current duration.
flutter: PlayerEvent.duration
flutter: PlayerEvent.position
flutter: PlayerEvent.position
flutter: PlayerEvent.duration
flutter: PlayerEvent.position
AudioPlayers: Could not set playback to position 0 and rate 1.000000.)
 
and my sound dont loop

**Comment by mohamadlounnas** [comment]
Can you provide more information?
package and flutter version, also platform?
