### ISSUE TITLE
Loop parameter not working

### ISSUE THREAD

**Issue by Syooian** [physia/kflutter#23]
Loop parameter not working in Player.create,
need to set loop = true after init()

**Comment by mohamadlounnas** [comment]
Can you provide more information?
platform, version and if possible example of the code you used

**Comment by mohamadlounnas** [comment]
thanks @Syooian 
bug fixed
https://pub.dev/packages/kplayer

**Comment by Syooian** [comment]
Hi, what Flutter version did you used? I can't use 0.3.0 in stable channel so just change to beta channel (looks like Dart version need 2.18.0 and stable channel is using 2.17.6), and loop parameter still not work, 
can't use
`audioPlayer.loop = true;`
stuck, in ticker.dart
```
  void _complete() {
    assert(_completed == null);
    _completed = true;
    _primaryCompleter.complete(); <====here
    _secondaryCompleter?.complete();
  }
```

Did I missed something?

**Comment by mohamadlounnas** [comment]
i think just_audio clear the audio when completed, i found a way around that
it should work now,
I'm still doing some tests, you can try this for now
kplayer v0.3.3

**Comment by Syooian** [comment]
Great, it's work in beta channel, thanks. :)

**Comment by mohamadlounnas** [comment]
fixed https://github.com/physia/kflutter/commit/a695c445aedb4785205f9e6e82aaef1f526b9b72
