### ISSUE TITLE
loop: true does not work in windows.

### ISSUE THREAD

**Issue by stabjul** [physia/kflutter#24]
When an audio asset is passed to Player, like -
player = Player.create(media: PlayerMedia.asset("assets/audio/ring.mp3"), loop: true)..init();
The audio loops for all platforms(Android, macOS) except windows.
Any plans to add a loop in windows?
Any workarounds to make the loop work in windows?

**Comment by mohamadlounnas** [comment]
loop should works in windows, Maybe something is wrong
I'll take a look at it

**Comment by mohamadlounnas** [comment]
fixed https://github.com/physia/kflutter/commit/a695c445aedb4785205f9e6e82aaef1f526b9b72
