### ISSUE TITLE
Excessive Logging of Player Events During Playback

### ISSUE THREAD

**Issue by calcitem** [physia/kflutter#29]
Hello `kplayer` Team,

First of all, thank you for your work on `kplayer`; it's a great asset to the Flutter community.

I'm currently integrating `kplayer` into my Flutter project to handle audio playback. Everything is functioning as expected, however, I've encountered an issue with excessive logging of player events during playback. While playing audio, the console is flooded with logs for every minor event (`PlayerEvent.status`, `PlayerEvent.play`, `PlayerEvent.init`, `PlayerEvent.position`, etc.), which makes it challenging to read other important logs for debugging purposes.

Here is an example of the logs I'm seeing:

```
flutter: PlayerEvent.status
flutter: PlayerEvent.play
flutter: PlayerEvent.init
flutter: PlayerEvent.position
... (many more lines of similar logs)
```

This occurs whenever I play an audio file using `kplayer`. While I understand the importance of these events for internal state management and potentially for debugging, it would be immensely helpful to have a way to control the verbosity of these logs, either by:
- Providing an option to disable or reduce the logging of these events.
- Implementing log levels that allow developers to choose the amount of detail they want in the logs.
- Any other solution that would allow controlling or filtering these logs without losing critical information about errors or significant state changes.

I believe such a feature would be beneficial for many developers who use `kplayer` in more complex applications where console output is already quite dense.

Thank you for considering this request. I look forward to any suggestions or updates you might have.

```
kplayer: ^0.4.2


[✓] Flutter (Channel stable, 3.19.4, on macOS 14.3.1 23D60 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.19.4 on channel stable at /Users/calcitem/development/flutter
    • Upstream repository https://gitee.com/mirrors/Flutter.git
    • FLUTTER_GIT_URL = https://gitee.com/mirrors/Flutter.git
    • Framework revision 68bfaea224 (11 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/calcitem/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] VS Code (version 1.81.1)
    • VS Code at /Users/calcitem/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • 2206122SC (mobile) • 40a6e11a                  • android-arm64  • Android 13 (API 33)
    • iPhone Xs (mobile) • 00008020-000A54E8363B002E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)    • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 123.0.6312.87
    ! Error: Browsing on the local area network for iPad Pro (2). Ensure the device is unlocked and attached with a
      cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by mohamadlounnas** [comment]
hi @calcitem ,
Firstly, thank you. I appreciate your words.
Secondly, you're right, it can be too much. I made some changes and upgraded the packages. I'll upload it very soon

**Comment by mohamadlounnas** [comment]
I forgot to mention that you can simply add the following line at the beginning of `main()`:
```dart
PlayerController.enableLog = false;
```
or just override the `callback` function in `PlayerController.callback`

**Comment by calcitem** [comment]
> PlayerController.enableLog = false;

It works! Thank you!
