### ISSUE TITLE
not support macos

### ISSUE THREAD

**Issue by 3215466800** [physia/kflutter#3]
not support macos

**Comment by mohamadlounnas** [comment]
hi, it should sopport mac os, cs we use dart vlc it support mac os, but we are not able to test on macos
try update to latest version

**Comment by mohamadlounnas** [comment]
u can use (depend on dart_vlc, and just_audio)
https://pub.dev/packages/kplayer
or (only audioplayers)
https://pub.dev/packages/kplayer_with_audioplayers

the same interface

**Comment by Andresit0** [comment]
I have this error with flutter 3.0.0 and macos (I'm using kplayer: ^0.1.19)

CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
    -> Fetching podspec for `audio_session` from `Flutter/ephemeral/.symlinks/plugins/audio_session/macos`
    -> Fetching podspec for `dart_vlc` from `Flutter/ephemeral/.symlinks/plugins/dart_vlc/macos`
    -> Fetching podspec for `just_audio` from `Flutter/ephemeral/.symlinks/plugins/just_audio/macos`
    -> Fetching podspec for `path_provider_macos` from `Flutter/ephemeral/.symlinks/plugins/path_provider_macos/macos`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_5_f_4.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/5/f/4/VLCKit/3.4.1b9/VLCKit.podspec.json exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "just_audio":
      In Podfile:
        just_audio (from `Flutter/ephemeral/.symlinks/plugins/just_audio/macos`)

    Specs satisfying the `just_audio (from `Flutter/ephemeral/.symlinks/plugins/just_audio/macos`)` dependency were found, but they required a higher minimum
    deployment target.

    /Users/andres/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Users/andres/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    /Users/andres/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
    /Users/andres/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Users/andres/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
    /Users/andres/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Users/andres/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Users/andres/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
    /Users/andres/.gem/ruby/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `<main>'

Error output from CocoaPods:
↳
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21/rbconfig.rb:230: warning: Insecure world writable dir
    /Users/andres/Documents/programasMAC/flutter/bin in PATH, mode 040777

**Comment by mohamadlounnas** [comment]
can you try the latest version v0.2.0?

**Comment by Andresit0** [comment]
I was able to build the project example when macos/Podfile replace platform :osx, '10.11' to platform :osx, '10.15'. Furthermore, adding to macos/Runner/DebugProfile.entitlements and macos/Runner/Release.entitlements:

<key>com.apple.security.network.client</key>
<true/>

**Comment by mohamadlounnas** [comment]
> I was able to build the project example when macos/Podfile replace platform :osx, '10.11' to platform :osx, '10.15'. Furthermore, adding to macos/Runner/DebugProfile.entitlements and macos/Runner/Release.entitlements:
> 
> ```
> <key>com.apple.security.network.client</key>
> <true/>
> ```

did the exmaple work fine on runtime?

**Comment by Andresit0** [comment]
Yes, it works fine with that changes

> > I was able to build the project example when macos/Podfile replace platform :osx, '10.11' to platform :osx, '10.15'. Furthermore, adding to macos/Runner/DebugProfile.entitlements and macos/Runner/Release.entitlements:
> > ```
> > <key>com.apple.security.network.client</key>
> > <true/>
> > ```
> 
> did the exmaple work fine on runtime?

**Comment by mohamadlounnas** [comment]
@Andresit0 if you face a problem with `just_audio` you can use `audioplayers` only
in v0.2.2 you can specify which package for every platform:
```dart
Player.platforms[PlatformEnv.macos] = PlayerAdaptivePackage(
    factory: just_audio.Player.new,
    name: 'audioplayers',
);
```

for use `audioplayers` only use [kplayer_with_audioplayers](https://pub.dev/packages/kplayer_with_audioplayers)
it has the same api.
