### ISSUE TITLE
Need help in creating Volume control plugin mainly for Windows ,other also

### ISSUE THREAD

**Issue by Manishmg3994** [physia/kflutter#7]
I fond there is no volume control plugins  for windows in pub dev but you can create that one or you will send those source code to me at manishgautammg7@gmail.com

**Comment by mohamadlounnas** [comment]
Hi
Id didn't understand, you want to change the volume of the system or the player?
In the player just use `player. volume=<VALUE>`
But for system volume u need to use an external plugin like Win32

**Comment by Manishmg3994** [comment]
A custom plugin to control system volume <desktop>

**Comment by mohamadlounnas** [comment]
i found this plugin
https://pub.dev/packages/sound_volume_view
