### ISSUE TITLE
Player.network work on Linux but not on Windows

### ISSUE THREAD

**Issue by poka-IT** [physia/kflutter#9]
I notice that reading from network works fine on Linux, but not on Windows, with the same code.

It is as if the request did not execute at all (nothing appears in the devtools), no error appears in the logs so it is very difficult to diagnose.

I would like to give more information but unfortunately I don't have it.

Other query types work fine in the app on Windows.

Has anyone else had success getting network play to work on a Windows build?

**Comment by mohamadlounnas** [comment]
it should work, Have you tried the example?
https://github.com/physia/kflutter/tree/main/kplayer/kplayer/example

**Comment by mohamadlounnas** [comment]
TLS handshake error happened because of problem in ssl certificate
u have problem with ssl certificate from archive.org
can u try another file ?

**Comment by poka-IT** [comment]
I know this is a certificate error, but the problem is same for all domain and file I test with kflutter.
Maybe the problem is in my system, but it's strange that it only happens with kflutter.

**Comment by mohamadlounnas** [comment]
can u try this?
https://pub.dev/packages/kplayer_with_audioplayers
it has the some methods just for audioplayers packege

**Comment by poka-IT** [comment]
I want to, but I don't understand how to use it.
There is no `PlayerController` type, and the `Player` class only contains a `players` attribute which is a getter that returns a `List<PlayerController>`, that I can't instantiate.

So I don't know what to do with it ?

**Comment by mohamadlounnas** [comment]
about ur previous issue i forget to remove unused dependencies from the example specifically "**audioplayers**"
know the main packege should work fine

2) about [kplayer_with_audioplayers](https://pub.dev/packages/kplayer_with_audioplayers) it has main `class Player extends PlayerController`,
if u want to use it just use:
```
var player = Player(
     media:  // PlayerMedia
);
player.init();
player.play();
```
the rest is the some

**Comment by poka-IT** [comment]
I'm stick on Nuget.exe issue again and can't resolve it, cleanning Nuget package cache, repair VS, flutter clean et pug get, windows folder deleting and rebuild, nothing seems to resolv this now...
So I tell you when I solve this problem.

```
Launching lib\main.dart on Windows in debug mode...
Nuget.exe not found, trying to download or use cached version.
C:\Users\poka\dev\fipy\build\windows\packages\Microsoft.Windows.ImplementationLibrary\include\wil/cppwinrt.h(82,75): error C2338: Please include wil/cppwinrt.h before including any C++/WinRT headers [C:\Users\poka\dev\fipy\build\windows\plugins\audioplayers_windows\audioplayers_windows_plugin.vcxproj]
C:\Users\poka\dev\fipy\build\windows\packages\Microsoft.Windows.ImplementationLibrary\include\wil/cppwinrt.h(101,75): error C2338: C++/WinRT external catch clause already defined outside of WIL [C:\Users\poka\dev\fipy\build\windows\plugins\audioplayers_windows\audioplayers_windows_plugin.vcxproj]
C:\Users\poka\dev\fipy\build\windows\packages\Microsoft.Windows.ImplementationLibrary\include\wil/cppwinrt.h(82,75): error C2338: Please include wil/cppwinrt.h before including any C++/WinRT headers [C:\Users\poka\dev\fipy\build\windows\plugins\audioplayers_windows\audioplayers_windows_plugin.vcxproj]
C:\Users\poka\dev\fipy\build\windows\packages\Microsoft.Windows.ImplementationLibrary\include\wil/cppwinrt.h(101,75): error C2338: C++/WinRT external catch clause already defined outside of WIL [C:\Users\poka\dev\fipy\build\windows\plugins\audioplayers_windows\audioplayers_windows_plugin.vcxproj]
Exception: Build process failed.
Exited (sigterm)
```

**Comment by poka-IT** [comment]
Ok i'm found a solution for this problem: https://github.com/bluefireteam/audioplayers/issues/1114#issuecomment-1118841415
So now it's working fine with audioplayer, no more certificate issue.

Is it possible to use `kplayer_with_audioplayers` in stable channel ?

**Comment by mohamadlounnas** [comment]
yes palning to do use it but `kplayer_with_audioplayers ` not support headers
currently only just_audio support http headers,

In case you need authentication, you can pass token in parameters but an ugly way to do it.
Until finding a better solution `kplayer_with_audioplayers `will keep get updates

`kplayer_with_audioplayers`
`kplayer_with_dart_vlc`
`kplayer_with_just_audio`

all of them implements `kplayer_platform_interface` u can just replace any one by other 
if we add support to video the api will still the same

the main packege binding `kplayer_with_dart_vlc `and `kplayer_with_just_audio` to support all platforms 
but `kplayer_with_audioplayers` allready support all platforms so you can use it directly
